### ISSUE TITLE
CSS issue with Other Devices and Recently Closed buttons

### ISSUE THREAD

**Issue by egret85** [egret85/ClassicNewTabPage#21]
The arrow on the buttons is displaying on another line from the button text.  Need to Fix CSS for these buttons so that it displays correctly.

Currently looks like this: 
![current css](https://cloud.githubusercontent.com/assets/5412571/5631549/8cd7ad96-9595-11e4-81ad-02bbe207480e.png)

Should look like this:
![original ntp](https://cloud.githubusercontent.com/assets/5412571/5631550/8cdb8056-9595-11e4-8df5-1d47dbae89e1.png)

**Comment by egret85** [comment]
@vehystrix could you take a look look at this since you created the new buttons?

**Comment by vehystrix** [comment]
I'll take a look at it, but at first glance it looks like it'll take some css black magic wizardry to get it to work properly

**Comment by Jeremy-D-Miller** [comment]
@egret85 Would it be possible to roll up a release with the latest changes (specifically this one) and put in on the Chrome App Store?  I understand you had some other things in this milestone but it's been over a year now since the last release.  I know how life gets in the way sometimes and I can run my own build, but the Developer Channel of Chrome has been complaining about unsigned extensions at every launch now for a few months now.

Alternatively @vehystrix, would you mind rolling a build with a new key from your repo and releasing it separately?  I understand they've bumped up security a bit (which is a good thing) but I'm not currently registered with the Chrome App Store and figured you might be.

Alternatively, alternatively, just say the word and I can fork and create my own release.

Thanks!

**Comment by egret85** [comment]
V1.1.4 has been published and should show up in the store soon.  I havn't really had the time to keep up with development of this as I had planned.  I will however continue to review pull requests and push updates to the store as needed.

**Comment by Jeremy-D-Miller** [comment]
Awesome!  I completely understand that there is never enough time (esp. for personal coding projects).  I just figured since it was already in the repo might as well publish it.  Thanks Everette.
